Auth/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'Auth'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('account/', views.AccountView.as_view(), name='account'),
]

Nutella/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'Nutella'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('legals/', views.LegalView.as_view(), name='legals'),
    path('results/', views.ResultsView.as_view(), name='results'),
    path('saved_food/', views.SavedFoodView.as_view(), name='saved_food'),
    path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('delete/<int:product_id>', views.DeleteView.as_view(), name='delete'),
    path('add_to_favorite/<int:product_id>',
         views.AddToFavoriteView.as_view(), name='add_to_favorite'),
]

Projet_08/Nutella/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'Nutella'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('legals/', views.LegalView.as_view(), name='legals'),
    path('results/', views.ResultsView.as_view(), name='results'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('saved_food/', views.SavedFoodView.as_view(), name='saved_food'),
    path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('delete/<int:product_id>', views.DeleteView.as_view(), name='delete'),
    path('add_to_favorite/<int:product_id>',
         views.AddToFavoriteView.as_view(), name='add_to_favorite'),
]

Nutella/models.py
from django.db import models
from Auth.models import MyUser


class Category(models.Model):
    """
    Creates categories for our food products.
    """
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Creates products objects for each food collected and inserted in
    our database.
    """
    name = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    nutri_grade = models.CharField(max_length=10)
    url = models.URLField()
    stores = models.CharField(max_length=200)
    ingredients = models.TextField()
    image_small = models.URLField()
    image_xl = models.URLField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    users = models.ManyToManyField(MyUser, related_name='favorites')
    code = models.CharField(max_length=50, null=True)
    date = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    def get_better_food(self, product):
        """
        Method required to look for better food in the database.
        It is based on the category of the product given by the
         user of the website.
        """
        category = product.category
        result = Product.objects.filter(category=category)
        return result.order_by('nutri_grade')

Nutella/forms.py
from django import forms


# Models for the forms of website
class ContactForm(forms.Form):
    """
    A basic contact form. Not implemented on the first version of the app.
    """
    email = forms.EmailField(label='Votre adresse mail ')
    message = forms.CharField(widget=forms.Textarea, label='Dites nous tout! ')


class SearchForm(forms.Form):
    """
    The form designed to look for an healthier product as the user enters
    his search in.
    """
    search = forms.CharField(initial='Produit', label='')

Nutella/views.py
from django.shortcuts import reverse, redirect, get_object_or_404
from django.views.generic.edit import FormView, BaseFormView
from django.views.generic import TemplateView, DetailView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponseRedirect

from .models import Product
from .forms import ContactForm, SearchForm
from django.conf import settings


# context_processors functions
def navbar_search_form(request):
    search_form = SearchForm()
    return {'search_form': search_form}


# Create your views here.
class IndexView(FormView):
    """
    Simple homepage view for the website.
    Contains a form to search for food products.
    """
    form_class = SearchForm
    template_name = 'Nutella/index.html'


class LegalView(TemplateView):
    """
    This view displays legal content for this
     website.
    """
    template_name = 'Nutella/legals.html'


class ContactView(FormView):
    """
    A view to display contact form.
    Currently not working in this version.
    """
    template_name = 'Nutella/contact.html'
    form_class = ContactForm
    success_url = '/'
    
    def post(self, request):
        user = request.POST['email']
        message = "This is an automated reply sent from Pur Beurre Website.\
    \nWe will soon answer you! Thank you for supporting 'Pur Beurre!'\n"
        message += request.POST['message']
        email_from = settings.EMAIL_HOST_USER
        if user and message:
            send_mail(
            'Reply from Pur Beurre',
            message,
            email_from,
            [user, email_from],
            fail_silently=True,
            )
            messages.success(request, f"Merci pour votre message {user}!")
            return redirect(reverse('Nutella:index',))
        else:
            form = ContactForm()
        messages.info(request, 'Une erreur est survenue. Veuillez réessayer!')
        return render(request, template_name, {'form': form})


class ProductView(DetailView):
    """
    Displays details about a product.
    Needs a product_id to be sent in request.
    """
    template_name = 'Nutella/product.html'
    model = Product


class SavedFoodView(LoginRequiredMixin, ListView):
    """
    Displays all the food products already saved by the logged in
     user. If not any, displays an alternative page.
    """
    login_url = '/login/'
    paginate_by = 6
    template_name = 'Nutella/saved_food.html'
    context_object_name = 'products'

    def get_queryset(self):
        "This is where we try to retrieve already saved products."
        return Product.objects.filter(users=self.request.user).order_by('pk')


class AddToFavoriteView(LoginRequiredMixin, View):
    """
    Creates a relation between an existing product and an
     identified user.
    """
    
    login_url = '/login/'

    def post(self, request, product_id):
        """
        No GET method here. Only POST. To prevent XSS. Try to add
         a new relation in the users(favorites) product field. Display
         a message if success or not. Can also manage cases when the
         selected product is already saved.
        """
        product = get_object_or_404(Product, pk=product_id)
        if request.user in product.users.all():
            messages.info(request, "Cet aliment est déjà dans vos favoris!")
        else:
            try:
                product.users.set((request.user,))
            except KeyError:
                messages.info(request, "Une erreur s'est produite!")
            else:
                product.save()
                messages.success(
                    request,
                    "Cet aliment a été ajouté à votre liste!"
                    )
        return HttpResponseRedirect(reverse('Nutella:results'))


class DeleteView(View):
    """
    Removes selected relation between identified user and an already
     saved product.
    """

    def post(self, request, product_id):
        """
        Handles the product_id given by the request and try to remove
         existing relation between the user and this product.
        Displays message for success or not.
        """
        product = get_object_or_404(Product, pk=product_id)
        try:
            product.users.remove(request.user)
        except KeyError:
            messages.info(request, "Une erreur s'est produite!")
        else:
            product.save()
            messages.success(request, "Aliment supprimé de votre liste!")
            return redirect(reverse('Nutella:saved_food'))


class ResultsView(ListView, BaseFormView):
    """
    Displays the products found with the search terms of the user.
    Look for better food products in our database. Also save the
    results of it by saving search_term's informations and results
    in the session object.
    """

    template_name = 'Nutella/results.html'
    context_object_name = 'products'
    paginate_by = 6
    form_class = SearchForm

    def get_queryset(self):

        context = self.request.session['last_search']
        search_terms = context['search_terms']
        result = self.search_product(search_terms)
        return result

    def search_product(self, search):

        products = Product.objects.filter(name__icontains=search)
        if products:
            product = products.first()
            return product.get_better_food(product).all()
        else:
            return []

    def form_valid(self, form):

        search_terms = form.cleaned_data.get('search')
        self.request.session['last_search'] = {'search_terms': search_terms}
        return self.get(self.request)

Nutella/templates/Nutella/base.html
{% load static %}

<!-- Basic base template for our pages-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pur Beurre</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Compiled and minified Materialize CSS & JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'Nutella/css/styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'Nutella/css/materialize.css' %}">
        <link rel="icon" href="{% static 'Nutella/favicon.png' %}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <img src="{% static 'Nutella/img/pur_beurre.png' %}" alt="Logo" id="logo">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Pur Beurre</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger"><form action="{% url 'Nutella:results' %}" method="POST">{% csrf_token %}{{ search_form }}</form></a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item" id="account"><a class="nav-link js-scroll-trigger" href="{% url 'Auth:account' %}"><i class='far fa-user' style='font-size:24px;' title="Mon compte"></i></a></li>
                            <li class="nav-item" id="savedfood"><a class="nav-link js-scroll-trigger" href="{% url 'Nutella:saved_food' %}"><i class="fas fa-carrot" style="font-size: 24px;" title="Mes aliments"></i></a></li>
                            <li class="nav-item" id="logout">
                                    <form action="{% url 'Auth:logout' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" value="Déconnexion">
                                        <a class="nav-link js-scroll-trigger" href="#" onclick="document.forms[1].submit();return false;"><i class="fas fa-sign-out-alt" style="font-size: 24px;" title="Déconnexion"></i></a>
                                    </form>
                
                                    </li>
                        {% else %}
                            <li class="nav-item" id="login"><a class="nav-link js-scroll-trigger" href="{% url 'Auth:login' %}">Se connecter</a></li>
                            <li class="nav-item" id="create"><a class="nav-link js-scroll-trigger" href="{% url 'Auth:register' %}">Créer un compte</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger {% block menu_active_accueil %}{% endblock %}" href="{% url 'Nutella:index' %}">Accueil</a></li>
                        {% endif %}
                        {% if messages %}
                            {% for message in messages %}
                            <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:3000});</script>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container">
                <div class="row small text-center text-muted" id="footspace">
                    <a href="{% url 'Nutella:legals' %}">Mentions légales</a>
                    <a href="{% url 'Nutella:contact' %}">Contact</a>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Nutella/js/scripts.js' %}"></script>
        
    </body>
</html>

Nutella/templates/Nutella/contact.html
{% extends 'Nutella/base.html' %}
{% load static %}
{% block content %}

<!-- Form to contact-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">Une question?</h1>
                <p class="text-white-75 font-weight-light mb-5">Contactez-nous!</p>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <form action="#" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary btn-md js-scroll-trigger" value="Envoyer">
                </form>
            </div>
        </div>
    </div>
</header>
{% endblock %}

Nutella/templates/Nutella/legals.html
{% extends 'Nutella/base.html' %}
{% load static %}
{% block content %}

<!-- This is where we put the legal mentions-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">

            <div class="col-lg-6 align-self-end">
                <h1 class="text-white font-weight-bold">Mentions légales</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-6 align-self-end">
                <h1 class="text-white font-weight-bold">Crédits</h1>
                <hr class="divider my-4" />
            </div>
            
            <div class="col-lg-6 align-self-middle">
                <p class="text-white-75 font-weight-bold mb-5">Propriétaires du restaurant Ratatouille et du site:</p>
                <p class="text-white-75 font-weight-light mb-5">Rémy Lerat & Colette Tatou</p>
                <p class="text-white-75 font-weight-light mb-5">SARL Pur Beurre - 7 cité de Paradis 75010 PARIS</p>
                <p class="text-white-75 font-weight-light mb-5">SIRET	49386136300064</p>
                <p class="text-white-75 font-weight-light mb-5">tél +33 - 1-48-45-67-32   mail: contact@ratatouille.com</p>
            </div>

            <div class="col-lg-6 align-self-middle">
                
                
                <p class="text-white-75 font-weight-bold mb-5">Apparence du site:</p>
                <p class="text-white-75 font-weight-light mb-5">Start Bootstrap (blackrockdigital.github.io), Font awesome (fontawesome.com), Iconarchive (iconarchive.com)</p>
                <p class="text-white-75 font-weight-bold mb-5">Données alimentaires issues de:</p>
                <p class="text-white-75 font-weight-light mb-5">Association OpenFoodFacts (fr.openfoodfacts.org)</p>
                <p class="text-white-75 font-weight-bold mb-5">Conception du site:</p>
                <p class="text-white-75 font-weight-light mb-5">Emmanuel Nocquet</p>
            </div>
            <div class="col-lg-10 align-self-middle">
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'Nutella:index' %}">Retourner à l'Accueil</a>
            </div>
        </div>
    </div>
</header>
{% endblock %}

Nutella/templates/Nutella/product.html
{% extends 'Nutella/base.html' %}
{% load static %}
{% block content %}

<!-- Masthead-->
<header class="masthead" style="height: 15vh; min-height: 10rem;">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-12 align-self-start">
                <h1 class="text-white font-weight-bold" id="foodname">{{ product.name }}</h1>
            </div>
        </div>
    </div>
</header>

<!-- User informations section-->
<section class="page-section" id="user_informations" style="min-height: 45rem; padding: 3rem 0;">
    <div class="container">
        <h2 class="text-center mt-0">Voici les informations disponibles sur ce produit</h2>
        <hr class="divider my-4" />
        <div class="row">
            <div class="col-lg-6 col-md-12 text-center">

                <!-- Display the right nutriscore image-->
                {% if product.nutri_grade == 'a' %}
                    <img src="{% static 'Nutella/img/nutriscore-a.svg' %}">
                {% elif product.nutri_grade == 'b' %}
                    <img src="{% static 'Nutella/img/nutriscore-b.svg' %}">
                {% elif product.nutri_grade == 'c' %}
                    <img src="{% static 'Nutella/img/nutriscore-c.svg' %}">
                {% elif product.nutri_grade == 'd' %}
                    <img src="{% static 'Nutella/img/nutriscore-d.svg' %}">
                {% else %}
                    <img src="{% static 'Nutella/img/nutriscore-e.svg' %}">
                {% endif %}
                <img src="{{ product.image_xl }}" alt="{{ product.name }}">
            </div>

            <div class="col-lg-6 col-md-12 align-self-center text-center">
                <p><strong>Marque:</strong> {{ product.brand }}</p>
                <p><strong>Nutri score:</strong> {{ product.nutri_grade }}</p>
                <p><strong>Distribué dans les magasins:</strong> {{ product.stores }}</p>
                <p><strong>Ingrédients:</strong> {{ product.ingredients }}</p>
                <p><strong>Lien vers le site OpenFoodfacts:</strong> <a href="{{ product.url }}" style="color: black;">{{ product.url }}</a></p>
                <hr class="divider my-4" />
                
                <!-- If user unidentified, don't show the save button-->
                {% if user.name is not None %}
                    <p><form action="{% url 'Nutella:add_to_favorite' product.id %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary-second-s btn-md js-scroll-trigger" value="Sauvegarder cet aliment" id="save_btn">
                    </form></p>
                {% else %}
                    <p>
                        <a href="{% url 'Auth:login' %}">Se connecter pour commencer à sauvegarder des aliments!</a>
                    </p>
                {% endif %}

                <p><a href="{% url 'Nutella:results' %}">Retourner au résultat de la recherche</a></p>
                <p><a href="{% url 'Nutella:index' %}">Retourner à l'accueil</a></p>

            </div>
        </div>
    </div>
</section>
{% endblock %}

Nutella/templates/Nutella/results.html
{% extends 'Nutella/base.html' %}
{% load static %}
{% block content %}

<!-- The results page-->

<!-- Masthead-->
<header class="masthead" style="height: 15vh; min-height: 10rem;">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-start">
                <h1 class="text-white font-weight-bold">{{ last_search }}</h1>
            </div>
        </div>
    </div>
</header>

<!-- Results section-->

{% if products %}

    <section class="page-section" id="services" style="padding: 3rem 0; min-height: 45rem;">
        <div class="container">
            <h2 class="text-center mt-0">Vous pouvez remplacer cet aliment par ...</h2>
            <hr class="divider my-4" />
                <div class="row">

                {% for product in page_obj %}

                    <div class="col-lg-4 col-md-12 text-center align-self-end">
                        <div class="mt-5">
                            <a class="portfolio-box" href="{% url 'Nutella:product' product.id %}" id="result">

                                <!-- Display the right nutriscore image-->

                                {% if product.nutri_grade == 'a' %}
                                    <img src="{% static 'Nutella/img/nutri-a.png' %}" style="vertical-align: top;">
                                {% elif product.nutri_grade == 'b' %}
                                    <img src="{% static 'Nutella/img/nutri-b.png' %}" style="vertical-align: top;">
                                {% elif product.nutri_grade == 'c' %}
                                    <img src="{% static 'Nutella/img/nutri-c.png' %}" style="vertical-align: top;">
                                {% elif product.nutri_grade == 'd' %}
                                    <img src="{% static 'Nutella/img/nutri-d.png' %}" style="vertical-align: top;">
                                {% else %}
                                    <img src="{% static 'Nutella/img/nutri-e.png' %}" style="vertical-align: top;">
                                {% endif %}
                                
                                <img class="img" src="{{ product.image_small }}" alt="{{ product.image_small }}" title="{{ product.name }}">
                            </a>
                            <div class="portfolio-box-caption">
                                <h3 class="h4 mb-2">{{ product.name }}</h3>

                                <!-- If user unidentified, don't show the save button-->
                                {% if user.name is not None %}

                                <p class="text-muted mb-0 ">  
                                    <form action="{% url 'Nutella:add_to_favorite' product.id %}" method="POST">
                                        {% csrf_token %}
                                        <i style="font-size:24px; vertical-align: auto;" class="fa">&#xf0c7;</i>
                                        <input type="submit" class="btn btn-primary-second btn-xs" value="Sauvegarder">
                                    </form>
                                </p>

                                {% else %}

                                <p>
                                    <a href="{% url 'Nutella:product' product.id %}">Voir ce produit</a>
                                </p>

                                {% endif %}

                            </div>
                        </div>
                    </div>

                {% endfor %}

                </div>
                <div class="pagination mt-5" style="justify-content: center;">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; Page 1</a>
                            <a href="?page={{ page_obj.previous_page_number }}">Page précédente</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">page suivante</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">Dernière page &raquo;</a>
                        {% endif %}
                    </span>
                </div>

        </div>
    </section>

{% else %}

<!-- Case no results section-->

<section class="page-section" id="user_informations" style="height: 45vh; min-height: 45rem; padding: 3rem 0;">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h2 class="text-center mt-0">Nous n'avons trouvé aucun produit pour votre recherche...</h2>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <img src="{% static 'Nutella/img/remy-5.jpg' %}" alt="Photo de Rémy">
                           
                <h3 class="h4 mb-2"><a href="{% url 'Nutella:index' %}">Effectuer une nouvelle recherche?</a></h3>
            </div>
        </div>
    </div>
</section>

{% endif %}

{% endblock %}

Nutella/templates/Nutella/saved_food.html
{% extends 'Nutella/base.html' %}
{% load static %}
{% block content %}

<!-- The saved food page-->

<!-- Masthead-->
<header class="masthead" style="height: 15vh; min-height: 10rem;">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-start">
                <h1 class="text-white font-weight-bold">Vos aliments sauvegardés!</h1>
            </div>
        </div>
    </div>
</header>

<!-- Results section if saved products found with this account-->
{% if products %}
<section class="page-section" id="services" style="padding: 3rem 0; min-height: 45rem;">
    <div class="container">
        <h2 class="text-center mt-0">Voici les aliments enregistrés lors de vos précédentes visites <strong>{{ user.name }}</strong>!</h2>
        <hr class="divider my-4" />
        <div class="row">

            {% for product in page_obj %}

                <div class="col-lg-4 col-md-12 text-center align-self-end">
                    <div class="mt-5">
                        <a class="portfolio-box" href="{% url 'Nutella:product' product.id %}" id="to_product_info">
                            <img class="img-fluid" src="{{ product.image_small }}" alt="{{ product.image_small }}">
                        </a>
                        <div class="portfolio-box-caption">
                            <h3 class="h4 mb-2">{{ product.name }}</h3>
                            <p class="text-muted mb-0 ">  
                                <form action="{% url 'Nutella:delete' product.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary-second btn-xs" value="Supprimer de ma liste">
                                </form>
                            </p>
                        </div>
                    </div>
                </div>

            {% endfor %}
        
        </div>
        <div class="pagination mt-5" style="justify-content: center;">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Première page</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Page précédente</a>
                {% endif %}
        
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Page suivante</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Dernière page &raquo;</a>
                {% endif %}
            </span>
        </div>

    </div>
</section>

<!-- Results section if no saved products found with this account-->
{% else %}
<section class="page-section" id="user_informations" style="height: 45vh; min-height: 45rem; padding: 3rem 0;">
    <div class="container">
        <h2 class="text-center mt-0">Nous n'avons trouvé aucun produit sauvegardé <strong>{{ user.name }}</strong>!</h2>
        <hr class="divider my-4" />
        <div class="row">
            <div class="col-lg-6 col-md-12 text-center"><img src="{% static 'Nutella/img/remy-6.jpg' %}" alt="Photo de Rémy"></div>
            <div class="col-lg-6 col-md-12 align-self-center text-center">                        
                <h3 class="h4 mb-2"><a href="{% url 'Nutella:index' %}">Commencer votre recherche</a></h3>
                <p class="text-muted mb-0"></p>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endblock %}